export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"

# aliases
alias pipi="pip3 install"
alias ga="git add"
alias gs="git status"
alias gcm="git commit -m"
alias gcn="git commit --amend --no-edit"
alias gcb="git checkout -b"
alias gb="git branch"
alias gc="git checkout"
alias gplo="git pull origin"
alias gpso="git push -u origin"
alias cra="create-react-app"
alias icloud="cd /Users/wangonya/Library/Mobile\ Documents/com~apple~CloudDocs/"
alias lms="cd /Users/wangonya/Library/Mobile\ Documents/com~apple~CloudDocs/LMS\ Outputs/"
alias mrs="./manage.py runserver"
alias mmm="./manage.py makemigrations"
alias mm="./manage.py migrate"
alias mt="./manage.py test"
